// Generated by build/build.py — edit build/crops.py instead.
window.CROPS = [
 {
  "indoors": [
   1,
   2
  ],
  "sow": [],
  "transplant": [
   3,
   4,
   5,
   6,
   7
  ],
  "plant": [],
  "harvest": [
   6,
   7,
   8,
   9,
   10,
   11
  ],
  "id": "tomato",
  "name": "Tomato",
  "cat": "vegetable",
  "season": "warm",
  "days": "60–85 days from transplant",
  "sun": "Full sun",
  "spacing": "24–36 in",
  "tips": "Plant deep, burying most of the stem. In Claremont, fruit set stalls above ~92°F, so get plants in by April for early crops, then a second planting in late June–July for a fall harvest. Shade cloth helps in heat waves.",
  "wiki": "Tomato",
  "hydro": "both",
  "hydro_note": "A hydroponic classic. Start from seed, or root side-shoot 'suckers' in water in about a week. Choose compact or determinate varieties for small systems.",
  "img": "images/tomato.jpg",
  "credit": {
   "file": "Tomato_je.jpg",
   "artist": "Softeis",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Tomato_je.jpg"
  }
 },
 {
  "indoors": [
   1,
   2,
   3
  ],
  "sow": [],
  "transplant": [
   4,
   5,
   6
  ],
  "plant": [],
  "harvest": [
   7,
   8,
   9,
   10,
   11
  ],
  "id": "pepper",
  "name": "Pepper (sweet & hot)",
  "cat": "vegetable",
  "season": "warm",
  "days": "60–90 days from transplant",
  "sun": "Full sun",
  "spacing": "18–24 in",
  "tips": "Wait until soil is warm (April+). Peppers love inland heat and often produce into November; many will overwinter in 10a if cut back.",
  "wiki": "Bell pepper",
  "hydro": "seeds",
  "hydro_note": "Grows very well from seed in Dutch buckets or deep water culture. Compact varieties suit small setups.",
  "img": "images/pepper.jpg",
  "credit": {
   "file": "Green-Yellow-Red-Pepper-2009.jpg",
   "artist": "Kham Tran - www.khamtran.com",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Green-Yellow-Red-Pepper-2009.jpg"
  }
 },
 {
  "indoors": [
   2,
   3
  ],
  "sow": [],
  "transplant": [
   4,
   5,
   6
  ],
  "plant": [],
  "harvest": [
   7,
   8,
   9,
   10
  ],
  "id": "eggplant",
  "name": "Eggplant",
  "cat": "vegetable",
  "season": "warm",
  "days": "65–80 days from transplant",
  "sun": "Full sun",
  "spacing": "24 in",
  "tips": "Needs real heat — perfect for inland valleys. Asian types are more productive than big globe varieties.",
  "wiki": "Eggplant",
  "hydro": "seeds",
  "hydro_note": "Works well from seed in Dutch buckets; needs support and plenty of light.",
  "img": "images/eggplant.jpg",
  "credit": {
   "file": "Solanum_melongena_24_08_2012_(1).JPG",
   "artist": "Joydeep",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Solanum_melongena_24_08_2012_(1).JPG"
  }
 },
 {
  "indoors": [],
  "sow": [
   3,
   4,
   5,
   6,
   7,
   8
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   5,
   6,
   7,
   8,
   9,
   10
  ],
  "id": "bush-bean",
  "name": "Green Beans",
  "cat": "vegetable",
  "season": "warm",
  "days": "50–60 days (bush), 60–70 (pole)",
  "sun": "Full sun",
  "spacing": "4–6 in",
  "tips": "Sow every 3 weeks for a steady supply. Pole beans produce longer; bush beans are faster. Mid-summer sowings benefit from afternoon shade.",
  "wiki": "Green bean",
  "hydro": "seeds",
  "hydro_note": "Bush beans do well from seed in media beds or Dutch buckets. Pole beans need a trellis.",
  "img": "images/bush-bean.jpg",
  "credit": {
   "file": "Heaps_of_beans.jpg",
   "artist": "",
   "license": "GFDL 1.2",
   "source": "https://commons.wikimedia.org/wiki/File:Heaps_of_beans.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   4,
   5,
   6
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   7,
   8,
   9,
   10
  ],
  "id": "lima-bean",
  "name": "Lima Beans",
  "cat": "vegetable",
  "season": "warm",
  "days": "75–90 days",
  "sun": "Full sun",
  "spacing": "6 in",
  "tips": "Need warmer soil than snap beans (65°F+). Pole limas do very well in Southern California.",
  "wiki": "Lima bean",
  "hydro": "seeds",
  "hydro_note": "Possible from seed in Dutch buckets, but yields are low for the space.",
  "img": "images/lima-bean.jpg",
  "credit": {
   "file": "Phaseoulus_lunatus.jpg",
   "artist": "Howard F. Schwartz, Colorado State University, Bugwood.org",
   "license": "CC BY 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Phaseoulus_lunatus.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   4,
   5,
   6,
   7
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   7,
   8,
   9,
   10
  ],
  "id": "cowpea",
  "name": "Black-eyed Peas (Cowpeas)",
  "cat": "vegetable",
  "season": "warm",
  "days": "60–90 days",
  "sun": "Full sun",
  "spacing": "4–6 in",
  "tips": "Extremely heat and drought tolerant — one of the easiest summer crops inland. Eat young pods, fresh shelled peas, or dry beans.",
  "wiki": "Black-eyed pea",
  "hydro": "seeds",
  "hydro_note": "Grows from seed in media beds. Vigorous, so give it room.",
  "img": "images/cowpea.jpg",
  "credit": {
   "file": "Black-eyed_peas_close_up.jpg",
   "artist": "Jud McCranie",
   "license": "CC BY-SA 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:Black-eyed_peas_close_up.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   3,
   4,
   5,
   6,
   7
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   6,
   7,
   8,
   9,
   10
  ],
  "id": "corn",
  "name": "Sweet Corn",
  "cat": "vegetable",
  "season": "warm",
  "days": "65–90 days",
  "sun": "Full sun",
  "spacing": "10–12 in, in blocks",
  "tips": "Plant in blocks of at least 4 rows for good pollination. Water deeply when tassels appear.",
  "wiki": "Sweet corn",
  "hydro": "no",
  "hydro_note": "Too tall and space-hungry, and too little yield per plant for home hydroponics.",
  "img": "images/corn.jpg",
  "credit": {
   "file": "VegCorn.jpg",
   "artist": "The original Uploader was wstoakLL at English Wikipedia",
   "license": "Public domain",
   "source": "https://commons.wikimedia.org/wiki/File:VegCorn.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   3,
   4,
   5,
   6,
   7
  ],
  "transplant": [
   4,
   5,
   6
  ],
  "plant": [],
  "harvest": [
   5,
   6,
   7,
   8,
   9,
   10
  ],
  "id": "cucumber",
  "name": "Cucumber",
  "cat": "vegetable",
  "season": "warm",
  "days": "50–65 days",
  "sun": "Full sun",
  "spacing": "12 in on trellis",
  "tips": "Trellising saves space and keeps fruit clean. Consistent water prevents bitterness. Sow again in July for fall cukes.",
  "wiki": "Cucumber",
  "hydro": "seeds",
  "hydro_note": "Excellent hydroponic crop from seed. Trellis it, and choose greenhouse or parthenocarpic varieties so no pollination is needed.",
  "img": "images/cucumber.jpg",
  "credit": {
   "file": "ARS_cucumber.jpg",
   "artist": "Stephen Ausmus, USDA ARS",
   "license": "Public domain",
   "source": "https://commons.wikimedia.org/wiki/File:ARS_cucumber.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   3,
   4,
   5,
   6,
   7,
   8
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   5,
   6,
   7,
   8,
   9,
   10
  ],
  "id": "zucchini",
  "name": "Zucchini & Summer Squash",
  "cat": "vegetable",
  "season": "warm",
  "days": "45–55 days",
  "sun": "Full sun",
  "spacing": "24–36 in",
  "tips": "One or two plants go a long way. A second sowing in July replaces plants lost to powdery mildew or squash bugs.",
  "wiki": "Zucchini",
  "hydro": "seeds",
  "hydro_note": "Possible from seed in large Dutch buckets, but plants sprawl and use lots of nutrients.",
  "img": "images/zucchini.jpg",
  "credit": {
   "file": "CSA-Striped-Zucchini.jpg",
   "artist": "Evan-Amos",
   "license": "Public domain",
   "source": "https://commons.wikimedia.org/wiki/File:CSA-Striped-Zucchini.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   4,
   5,
   6
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   8,
   9,
   10,
   11
  ],
  "id": "winter-squash",
  "name": "Winter Squash",
  "cat": "vegetable",
  "season": "warm",
  "days": "80–110 days",
  "sun": "Full sun",
  "spacing": "36–48 in",
  "tips": "Butternut and other C. moschata types resist squash vine borer and handle heat best. Harvest when the rind resists a fingernail.",
  "wiki": "Winter squash",
  "hydro": "no",
  "hydro_note": "Vines are too large for practical home hydroponics.",
  "img": "images/winter-squash.jpg",
  "credit": {
   "file": "Squashes.jpg",
   "artist": "Californiacondor",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Squashes.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   5,
   6
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   9,
   10
  ],
  "id": "pumpkin",
  "name": "Pumpkin",
  "cat": "vegetable",
  "season": "warm",
  "days": "90–120 days",
  "sun": "Full sun",
  "spacing": "4–6 ft",
  "tips": "For Halloween, sow late May to mid-June. Needs lots of space and deep watering.",
  "wiki": "Pumpkin",
  "hydro": "no",
  "hydro_note": "Far too large for home hydroponics.",
  "img": "images/pumpkin.jpg",
  "credit": {
   "file": "FrenchMarketPumpkinsB.jpg",
   "artist": "Infrogmation of New Orleans",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:FrenchMarketPumpkinsB.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   4,
   5,
   6
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   7,
   8,
   9
  ],
  "id": "cantaloupe",
  "name": "Cantaloupe & Melons",
  "cat": "vegetable",
  "season": "warm",
  "days": "75–90 days",
  "sun": "Full sun",
  "spacing": "24–36 in",
  "tips": "Inland heat makes the sweetest melons. Cut back water as fruit ripens for better flavor; ripe cantaloupes 'slip' off the vine.",
  "wiki": "Cantaloupe",
  "hydro": "seeds",
  "hydro_note": "Commercial greenhouses grow melons in substrate from seed. At home you need Dutch buckets, a strong trellis and slings for the fruit.",
  "img": "images/cantaloupe.jpg",
  "credit": {
   "file": "Meloen_vrucht_met_bloem.jpg",
   "artist": "Rasbak at Dutch Wikipedia",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Meloen_vrucht_met_bloem.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   4,
   5,
   6
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   7,
   8,
   9
  ],
  "id": "watermelon",
  "name": "Watermelon",
  "cat": "vegetable",
  "season": "warm",
  "days": "75–95 days",
  "sun": "Full sun",
  "spacing": "3–5 ft",
  "tips": "Ripe when the tendril nearest the fruit dries and the ground spot turns creamy yellow.",
  "wiki": "Watermelon",
  "hydro": "no",
  "hydro_note": "Vines and fruit are too big for practical home hydroponics.",
  "img": "images/watermelon.jpg",
  "credit": {
   "file": "Watermelon slice.jpg",
   "artist": "Mishra12krati",
   "license": "CC BY-SA 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:Watermelon_slice.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   4,
   5,
   6,
   7
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   7,
   8,
   9,
   10
  ],
  "id": "okra",
  "name": "Okra",
  "cat": "vegetable",
  "season": "warm",
  "days": "55–65 days",
  "sun": "Full sun",
  "spacing": "12–18 in",
  "tips": "Loves the hottest part of the yard. Pick pods at 2–4 inches every day or two or they turn woody.",
  "wiki": "Okra",
  "hydro": "seeds",
  "hydro_note": "Grows from seed in Dutch buckets but gets tall. Dwarf varieties work best.",
  "img": "images/okra.jpg",
  "credit": {
   "file": "Hong_Kong_Okra_Aug_25_2012.JPG",
   "artist": "Earth100",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Hong_Kong_Okra_Aug_25_2012.JPG"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   4,
   5,
   6
  ],
  "harvest": [
   9,
   10,
   11
  ],
  "id": "sweet-potato",
  "name": "Sweet Potato",
  "cat": "vegetable",
  "season": "warm",
  "days": "90–120 days from slips",
  "sun": "Full sun",
  "spacing": "12–18 in",
  "tips": "Plant rooted slips once soil is warm. Very heat tolerant. Dig before soil cools in fall and cure in a warm spot for 1–2 weeks.",
  "wiki": "Sweet potato",
  "hydro": "cuttings",
  "hydro_note": "Vine cuttings root in water in days and give endless edible greens. Growing the tubers themselves needs deep media or soil.",
  "img": "images/sweet-potato.jpg",
  "credit": {
   "file": "Ipomoea_batatas_006.JPG",
   "artist": "Llez",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Ipomoea_batatas_006.JPG"
  }
 },
 {
  "indoors": [
   1,
   2,
   3
  ],
  "sow": [],
  "transplant": [
   3,
   4,
   5,
   6
  ],
  "plant": [],
  "harvest": [
   6,
   7,
   8,
   9,
   10
  ],
  "id": "tomatillo",
  "name": "Tomatillo",
  "cat": "vegetable",
  "season": "warm",
  "days": "65–85 days from transplant",
  "sun": "Full sun",
  "spacing": "36 in",
  "tips": "Plant at least two — they need a partner to set fruit. Harvest when husks fill out and split.",
  "wiki": "Tomatillo",
  "hydro": "seeds",
  "hydro_note": "Grows from seed like tomatoes, but sprawls. Plant two for pollination.",
  "img": "images/tomatillo.jpg",
  "credit": {
   "file": "Tomatillo.jpg",
   "artist": "",
   "license": "Public domain",
   "source": "https://commons.wikimedia.org/wiki/File:Tomatillo.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   4,
   5,
   6
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   6,
   7,
   8,
   9,
   10
  ],
  "id": "malabar-spinach",
  "name": "Malabar Spinach",
  "cat": "vegetable",
  "season": "warm",
  "days": "60–70 days",
  "sun": "Full sun to part shade",
  "spacing": "12 in on trellis",
  "tips": "A heat-loving climbing vine that replaces spinach in summer, when true spinach bolts immediately.",
  "wiki": "Basella alba",
  "hydro": "both",
  "hydro_note": "Grows vigorously from seed, and stem cuttings root easily in water.",
  "img": "images/malabar-spinach.jpg",
  "credit": {
   "file": "Basella_alba-2.JPG",
   "artist": "",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Basella_alba-2.JPG"
  }
 },
 {
  "indoors": [],
  "sow": [
   4,
   5,
   6,
   7,
   8
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   6,
   7,
   8,
   9,
   10
  ],
  "id": "amaranth",
  "name": "Amaranth Greens",
  "cat": "vegetable",
  "season": "warm",
  "days": "30–45 days for greens",
  "sun": "Full sun",
  "spacing": "6–12 in",
  "tips": "Fast summer green that thrives in heat. Harvest young leaves repeatedly.",
  "wiki": "Amaranth",
  "hydro": "seeds",
  "hydro_note": "A fast leafy crop from seed in NFT channels or deep water culture.",
  "img": "images/amaranth.jpg",
  "credit": {
   "file": "Amaranthus_tricolor0.jpg",
   "artist": "Kurt Stüber [1]",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Amaranthus_tricolor0.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   1,
   2,
   3,
   9,
   10,
   11
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   3,
   4,
   5,
   6,
   11,
   12,
   1,
   2
  ],
  "id": "beet",
  "name": "Beets",
  "cat": "vegetable",
  "season": "cool",
  "days": "50–70 days",
  "sun": "Full sun",
  "spacing": "3–4 in",
  "tips": "Each 'seed' is a cluster — thin seedlings to one. Greens are edible too.",
  "wiki": "Beetroot",
  "hydro": "seeds",
  "hydro_note": "Beets are hard to grow in hydroponics. Greens do fine from seed; roots need a deep media bed.",
  "img": "images/beet.jpg",
  "credit": {
   "file": "Detroitdarkredbeets.png",
   "artist": "BriannaWalther",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Detroitdarkredbeets.png"
  }
 },
 {
  "indoors": [
   7,
   8,
   12
  ],
  "sow": [],
  "transplant": [
   9,
   10,
   1,
   2
  ],
  "plant": [],
  "harvest": [
   11,
   12,
   1,
   2,
   3,
   4,
   5
  ],
  "id": "broccoli",
  "name": "Broccoli",
  "cat": "vegetable",
  "season": "cool",
  "days": "60–90 days from transplant",
  "sun": "Full sun",
  "spacing": "18 in",
  "tips": "Fall-planted broccoli is the most reliable here. After cutting the main head, side shoots keep coming for weeks.",
  "wiki": "Broccoli",
  "hydro": "seeds",
  "hydro_note": "Works from seed in Dutch buckets or deep water culture, but plants are big and take a while.",
  "img": "images/broccoli.jpg",
  "credit": {
   "file": "Broccoli_and_cross_section_edit.jpg",
   "artist": "Fir0002",
   "license": "GFDL 1.2",
   "source": "https://commons.wikimedia.org/wiki/File:Broccoli_and_cross_section_edit.jpg"
  }
 },
 {
  "indoors": [
   6,
   7
  ],
  "sow": [],
  "transplant": [
   8,
   9,
   10
  ],
  "plant": [],
  "harvest": [
   12,
   1,
   2,
   3
  ],
  "id": "brussels",
  "name": "Brussels Sprouts",
  "cat": "vegetable",
  "season": "cool",
  "days": "90–110 days from transplant",
  "sun": "Full sun",
  "spacing": "24 in",
  "tips": "Needs a long cool season to form tight sprouts — plant early in fall. Can be hit-or-miss in inland heat.",
  "wiki": "Brussels sprout",
  "hydro": "no",
  "hydro_note": "Too big and slow (up to 5 months) to be worth it in hydroponics.",
  "img": "images/brussels.jpg",
  "credit": {
   "file": "Brussels_sprout_closeup.jpg",
   "artist": "Eric Hunt",
   "license": "CC BY 2.5",
   "source": "https://commons.wikimedia.org/wiki/File:Brussels_sprout_closeup.jpg"
  }
 },
 {
  "indoors": [
   7,
   8,
   12
  ],
  "sow": [],
  "transplant": [
   9,
   10,
   11,
   1,
   2
  ],
  "plant": [],
  "harvest": [
   12,
   1,
   2,
   3,
   4,
   5
  ],
  "id": "cabbage",
  "name": "Cabbage",
  "cat": "vegetable",
  "season": "cool",
  "days": "60–100 days from transplant",
  "sun": "Full sun",
  "spacing": "18–24 in",
  "tips": "Keep evenly watered to avoid split heads. Smaller early varieties mature faster before spring heat.",
  "wiki": "Cabbage",
  "hydro": "seeds",
  "hydro_note": "Possible from seed in deep water culture or media beds. Compact varieties work best.",
  "img": "images/cabbage.jpg",
  "credit": {
   "file": "Cabbage_and_cross_section_on_white.jpg",
   "artist": "fir0002  flagstaffotos [at] gmail.com\n\t\tCanon 20D + Sigma 150mm f/2.8",
   "license": "GFDL 1.2",
   "source": "https://commons.wikimedia.org/wiki/File:Cabbage_and_cross_section_on_white.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   1,
   2,
   3,
   4,
   8,
   9,
   10,
   11
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   1,
   2,
   3,
   4,
   5,
   6,
   7,
   11,
   12
  ],
  "id": "carrot",
  "name": "Carrots",
  "cat": "vegetable",
  "season": "cool",
  "days": "60–80 days",
  "sun": "Full sun",
  "spacing": "2–3 in",
  "tips": "Keep the seedbed moist until germination (up to 2 weeks) — a board or burlap over the row helps. Loose soil makes straight roots.",
  "wiki": "Carrot",
  "hydro": "no",
  "hydro_note": "Roots need deep, loose media. Mostly impractical except for short 'Paris Market' types in deep media beds.",
  "img": "images/carrot.jpg",
  "credit": {
   "file": "Vegetable-Carrot-Bundle-wStalks.jpg",
   "artist": "Evan-Amos",
   "license": "Public domain",
   "source": "https://commons.wikimedia.org/wiki/File:Vegetable-Carrot-Bundle-wStalks.jpg"
  }
 },
 {
  "indoors": [
   7,
   8,
   12
  ],
  "sow": [],
  "transplant": [
   9,
   10,
   1,
   2
  ],
  "plant": [],
  "harvest": [
   12,
   1,
   2,
   3,
   4
  ],
  "id": "cauliflower",
  "name": "Cauliflower",
  "cat": "vegetable",
  "season": "cool",
  "days": "60–85 days from transplant",
  "sun": "Full sun",
  "spacing": "18–24 in",
  "tips": "Fussier than broccoli; needs steady water and cool weather. Tie leaves over white heads to blanch them.",
  "wiki": "Cauliflower",
  "hydro": "seeds",
  "hydro_note": "Possible from seed, but big plants and a long season.",
  "img": "images/cauliflower.jpg",
  "credit": {
   "file": "Chou-fleur_02.jpg",
   "artist": "Coyau",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Chou-fleur_02.jpg"
  }
 },
 {
  "indoors": [
   1,
   6,
   7
  ],
  "sow": [],
  "transplant": [
   2,
   3,
   8,
   9
  ],
  "plant": [],
  "harvest": [
   11,
   12,
   1,
   5,
   6
  ],
  "id": "celery",
  "name": "Celery",
  "cat": "vegetable",
  "season": "cool",
  "days": "90–120 days from transplant",
  "sun": "Full sun to part shade",
  "spacing": "8–12 in",
  "tips": "Heavy feeder and heavy drinker. Harvest outer stalks as needed.",
  "wiki": "Celery",
  "hydro": "seeds",
  "hydro_note": "Grows well from seed in deep water culture. You can also regrow a store-bought celery base in water.",
  "img": "images/celery.jpg",
  "credit": {
   "file": "Celery_1.jpg",
   "artist": "Lombroso",
   "license": "Public domain",
   "source": "https://commons.wikimedia.org/wiki/File:Celery_1.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   2,
   3,
   4,
   5,
   8,
   9,
   10
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12
  ],
  "id": "chard",
  "name": "Swiss Chard",
  "cat": "vegetable",
  "season": "cool",
  "days": "50–60 days",
  "sun": "Full sun to part shade",
  "spacing": "12 in",
  "tips": "The most forgiving green for zone 10 — tolerates both heat and frost and often produces all year from one planting.",
  "wiki": "Chard",
  "hydro": "seeds",
  "hydro_note": "An easy, productive leafy green from seed. Harvest outer leaves again and again.",
  "img": "images/chard.jpg",
  "credit": {
   "file": "Chard_(Beta_vulgaris_var_cicla).jpg",
   "artist": "Neelix at English Wikipedia",
   "license": "Public domain",
   "source": "https://commons.wikimedia.org/wiki/File:Chard_(Beta_vulgaris_var_cicla).jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   2,
   3,
   8,
   9,
   10
  ],
  "transplant": [
   2,
   3,
   9,
   10
  ],
  "plant": [],
  "harvest": [
   1,
   2,
   3,
   4,
   5,
   6,
   11,
   12
  ],
  "id": "collards",
  "name": "Collard Greens",
  "cat": "vegetable",
  "season": "cool",
  "days": "60–80 days",
  "sun": "Full sun",
  "spacing": "18 in",
  "tips": "More heat tolerant than kale; harvest lower leaves continually.",
  "wiki": "Collard (plant)",
  "hydro": "seeds",
  "hydro_note": "Easy leafy green from seed in NFT or deep water culture.",
  "img": "images/collards.jpg",
  "credit": {
   "file": "Collard-Greens-Bundle.jpg",
   "artist": "Evan-Amos",
   "license": "Public domain",
   "source": "https://commons.wikimedia.org/wiki/File:Collard-Greens-Bundle.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   10,
   11,
   12
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   3,
   4,
   5
  ],
  "id": "fava",
  "name": "Fava Beans",
  "cat": "vegetable",
  "season": "cool",
  "days": "80–100 days",
  "sun": "Full sun",
  "spacing": "6 in",
  "tips": "A classic winter crop and great cover crop — fixes nitrogen for your summer tomatoes. Young leaves are edible too.",
  "wiki": "Vicia faba",
  "hydro": "no",
  "hydro_note": "Tall plants with low yield for the space. Better in the garden.",
  "img": "images/fava.jpg",
  "credit": {
   "file": "Broad bean pods (1).jpg",
   "artist": "Fumikas Sagisavas",
   "license": "CC0",
   "source": "https://commons.wikimedia.org/wiki/File:Broad_bean_pods_(1).jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   10,
   11,
   12
  ],
  "harvest": [
   5,
   6
  ],
  "id": "garlic",
  "name": "Garlic",
  "cat": "vegetable",
  "season": "cool",
  "days": "7–8 months",
  "sun": "Full sun",
  "spacing": "4–6 in",
  "tips": "Choose softneck or 'Creole'/'Turban' types suited to mild winters. Pre-chilling cloves in the fridge for 6 weeks improves bulbing. Harvest when half the leaves are brown.",
  "wiki": "Garlic",
  "hydro": "no",
  "hydro_note": "Bulbs need soil and a long cold season. Garlic greens can be sprouted in water, though.",
  "img": "images/garlic.jpg",
  "credit": {
   "file": "Garlic bulbs and cloves.jpg",
   "artist": "Ivar Leidus",
   "license": "CC BY-SA 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:Garlic_bulbs_and_cloves.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   2,
   3,
   8,
   9,
   10
  ],
  "transplant": [
   2,
   3,
   9,
   10,
   11
  ],
  "plant": [],
  "harvest": [
   1,
   2,
   3,
   4,
   5,
   10,
   11,
   12
  ],
  "id": "kale",
  "name": "Kale",
  "cat": "vegetable",
  "season": "cool",
  "days": "50–65 days",
  "sun": "Full sun to part shade",
  "spacing": "12–18 in",
  "tips": "Frost sweetens the flavor. Pick lower leaves and the plant keeps growing upward.",
  "wiki": "Kale",
  "hydro": "seeds",
  "hydro_note": "A top hydroponic green from seed. Very productive with cut-and-come-again harvests.",
  "img": "images/kale.jpg",
  "credit": {
   "file": "Boerenkool.jpg",
   "artist": "Rasbak",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Boerenkool.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   2,
   3,
   9,
   10
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   4,
   5,
   11,
   12
  ],
  "id": "kohlrabi",
  "name": "Kohlrabi",
  "cat": "vegetable",
  "season": "cool",
  "days": "45–60 days",
  "sun": "Full sun",
  "spacing": "6 in",
  "tips": "Harvest bulbs at 2–3 inches across, before they get woody.",
  "wiki": "Kohlrabi",
  "hydro": "seeds",
  "hydro_note": "Grows from seed in media beds or deep water culture. The bulb forms above the waterline.",
  "img": "images/kohlrabi.jpg",
  "credit": {
   "file": "Brassica_oleracea_var._gongylodes_(kohlrabi).jpg",
   "artist": "Unknown",
   "license": "CC0",
   "source": "https://commons.wikimedia.org/wiki/File:Brassica_oleracea_var._gongylodes_(kohlrabi).jpg"
  }
 },
 {
  "indoors": [
   7,
   8,
   12
  ],
  "sow": [],
  "transplant": [
   1,
   2,
   3,
   9,
   10
  ],
  "plant": [],
  "harvest": [
   1,
   2,
   3,
   4,
   5,
   6,
   7
  ],
  "id": "leek",
  "name": "Leeks",
  "cat": "vegetable",
  "season": "cool",
  "days": "100–120 days from transplant",
  "sun": "Full sun",
  "spacing": "6 in",
  "tips": "Plant seedlings deep in a trench and hill soil around the stems as they grow for long white shanks.",
  "wiki": "Leek",
  "hydro": "seeds",
  "hydro_note": "Possible from seed in media beds, but slow.",
  "img": "images/leek.jpg",
  "credit": {
   "file": "Leek_on_white_background_-_0947.jpg",
   "artist": "Amada44",
   "license": "CC BY-SA 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:Leek_on_white_background_-_0947.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   1,
   2,
   3,
   9,
   10,
   11,
   12
  ],
  "transplant": [
   1,
   2,
   3,
   9,
   10,
   11
  ],
  "plant": [],
  "harvest": [
   1,
   2,
   3,
   4,
   5,
   10,
   11,
   12
  ],
  "id": "lettuce",
  "name": "Lettuce",
  "cat": "vegetable",
  "season": "cool",
  "days": "30–60 days (leaf), 70+ (head)",
  "sun": "Full sun (part shade in spring)",
  "spacing": "8–12 in",
  "tips": "Sow small amounts every 2–3 weeks. Bolts fast once days hit the 80s — choose heat-tolerant types for spring.",
  "wiki": "Lettuce",
  "hydro": "seeds",
  "hydro_note": "The easiest hydroponic crop there is. From seed to harvest in 4–6 weeks in any system.",
  "img": "images/lettuce.jpg",
  "credit": {
   "file": "Iceberg_lettuce_in_SB.jpg",
   "artist": "en:User:Geographer",
   "license": "CC BY 1.0",
   "source": "https://commons.wikimedia.org/wiki/File:Iceberg_lettuce_in_SB.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   1,
   2,
   3,
   9,
   10,
   11
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   1,
   2,
   3,
   4,
   5,
   10,
   11,
   12
  ],
  "id": "mustard",
  "name": "Mustard Greens",
  "cat": "vegetable",
  "season": "cool",
  "days": "30–45 days",
  "sun": "Full sun",
  "spacing": "6 in",
  "tips": "Very fast and easy. Spicier when grown in warmer weather.",
  "wiki": "Brassica juncea",
  "hydro": "seeds",
  "hydro_note": "Fast and easy from seed. Great in NFT or deep water culture.",
  "img": "images/mustard.jpg",
  "credit": {
   "file": "Brassica juncea var. juncea.JPG",
   "artist": "Dalgial",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Brassica_juncea_var._juncea.JPG"
  }
 },
 {
  "indoors": [],
  "sow": [
   2,
   3,
   9,
   10,
   11
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   3,
   4,
   10,
   11,
   12,
   1
  ],
  "id": "bok-choy",
  "name": "Bok Choy",
  "cat": "vegetable",
  "season": "cool",
  "days": "45–60 days (baby: 30)",
  "sun": "Full sun to part shade",
  "spacing": "6–10 in",
  "tips": "Bolts in heat and long days, so fall sowing is the most reliable.",
  "wiki": "Bok choy",
  "hydro": "seeds",
  "hydro_note": "Excellent hydroponic crop from seed. Fast, compact and slow to bolt indoors.",
  "img": "images/bok-choy.jpg",
  "credit": {
   "file": "Bok_Choy_(49553125456).jpg",
   "artist": "spurekar",
   "license": "CC BY 2.0",
   "source": "https://commons.wikimedia.org/wiki/File:Bok_Choy_(49553125456).jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   1,
   2,
   3,
   9,
   10,
   11,
   12
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   1,
   2,
   3,
   4,
   10,
   11,
   12
  ],
  "id": "arugula",
  "name": "Arugula",
  "cat": "vegetable",
  "season": "cool",
  "days": "30–40 days",
  "sun": "Full sun to part shade",
  "spacing": "4 in",
  "tips": "Almost foolproof in winter. Reseeds itself if you let a few plants flower.",
  "wiki": "Eruca vesicaria",
  "hydro": "seeds",
  "hydro_note": "Very easy from seed, and fast (about 4 weeks).",
  "img": "images/arugula.jpg",
  "credit": {
   "file": "Рукола IMG20220523175141.jpg",
   "artist": "Сарапулов",
   "license": "CC BY 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:%D0%A0%D1%83%D0%BA%D0%BE%D0%BB%D0%B0_IMG20220523175141.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   1,
   2,
   9,
   10,
   11
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   11,
   12,
   1,
   2,
   3,
   4
  ],
  "id": "spinach",
  "name": "Spinach",
  "cat": "vegetable",
  "season": "cool",
  "days": "40–50 days",
  "sun": "Full sun to part shade",
  "spacing": "4–6 in",
  "tips": "Bolts quickly as days lengthen — a strictly fall/winter crop inland.",
  "wiki": "Spinach",
  "hydro": "seeds",
  "hydro_note": "Grows well from seed but prefers cool water. Keep the nutrient solution under 75°F or it bolts.",
  "img": "images/spinach.jpg",
  "credit": {
   "file": "Spinacia_oleracea_Spinazie_bloeiend.jpg",
   "artist": "Rasbak",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Spinacia_oleracea_Spinazie_bloeiend.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   10,
   11
  ],
  "transplant": [],
  "plant": [
   11,
   12,
   1
  ],
  "harvest": [
   5,
   6,
   7
  ],
  "id": "onion",
  "name": "Bulb Onions",
  "cat": "vegetable",
  "season": "cool",
  "days": "Harvest in late spring",
  "sun": "Full sun",
  "spacing": "4 in",
  "tips": "Use SHORT-DAY varieties (e.g. Texas Grano, Red Creole, Granex) — long-day types won't bulb this far south. Harvest when tops fall over.",
  "wiki": "Onion",
  "hydro": "no",
  "hydro_note": "Bulbing is impractical in hydroponics. Grow green onions instead.",
  "img": "images/onion.jpg",
  "credit": {
   "file": "Mixed_onions.jpg",
   "artist": "Colin",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Mixed_onions.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   1,
   2,
   3,
   4,
   8,
   9,
   10,
   11,
   12
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   1,
   2,
   3,
   4,
   5,
   6,
   10,
   11,
   12
  ],
  "id": "scallion",
  "name": "Green Onions",
  "cat": "vegetable",
  "season": "cool",
  "days": "60–70 days",
  "sun": "Full sun",
  "spacing": "1–2 in",
  "tips": "Grow almost year-round. You can even replant the root ends of store-bought scallions.",
  "wiki": "Scallion",
  "hydro": "both",
  "hydro_note": "Easy from seed, or regrow store-bought root ends in water over and over.",
  "img": "images/scallion.jpg",
  "credit": {
   "file": "CSA-Red-Spring-Onions.jpg",
   "artist": "Evan-Amos",
   "license": "Public domain",
   "source": "https://commons.wikimedia.org/wiki/File:CSA-Red-Spring-Onions.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   9,
   10,
   11
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   2,
   3,
   4,
   5
  ],
  "id": "parsnip",
  "name": "Parsnips",
  "cat": "vegetable",
  "season": "cool",
  "days": "100–120 days",
  "sun": "Full sun",
  "spacing": "3–4 in",
  "tips": "Always use fresh seed; germination is slow (up to 3 weeks).",
  "wiki": "Parsnip",
  "hydro": "no",
  "hydro_note": "A long taproot crop that needs deep soil.",
  "img": "images/parsnip.jpg",
  "credit": {
   "file": "Parsnips-1.jpg",
   "artist": "Quadell",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Parsnips-1.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   9,
   10,
   11,
   12,
   1,
   2
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   11,
   12,
   1,
   2,
   3,
   4,
   5
  ],
  "id": "pea",
  "name": "Peas",
  "cat": "vegetable",
  "season": "cool",
  "days": "55–70 days",
  "sun": "Full sun",
  "spacing": "2 in on trellis",
  "tips": "Snap and snow peas thrive in Claremont winters. Sow in early fall for a holiday crop and again in January for spring.",
  "wiki": "Pea",
  "hydro": "seeds",
  "hydro_note": "Grows from seed with a trellis. Pea shoots and microgreens are especially easy.",
  "img": "images/pea.jpg",
  "credit": {
   "file": "Peas_in_pods_-_Studio.jpg",
   "artist": "Bill Ebbesen",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Peas_in_pods_-_Studio.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   1,
   2,
   3,
   8,
   9
  ],
  "harvest": [
   5,
   6,
   11,
   12
  ],
  "id": "potato",
  "name": "Potatoes",
  "cat": "vegetable",
  "season": "cool",
  "days": "70–120 days",
  "sun": "Full sun",
  "spacing": "12 in",
  "tips": "Plant certified seed potatoes. Mid-winter planting beats the summer heat; a late-summer planting gives a fall crop. Hill soil over stems as they grow.",
  "wiki": "Potato",
  "hydro": "no",
  "hydro_note": "Possible commercially in aeroponics, but impractical at home.",
  "img": "images/potato.jpg",
  "credit": {
   "file": "Patates.jpg",
   "artist": "Scott Bauer, USDA ARS",
   "license": "Public domain",
   "source": "https://commons.wikimedia.org/wiki/File:Patates.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   1,
   2,
   3,
   4,
   9,
   10,
   11,
   12
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   1,
   2,
   3,
   4,
   5,
   10,
   11,
   12
  ],
  "id": "radish",
  "name": "Radishes",
  "cat": "vegetable",
  "season": "cool",
  "days": "25–30 days (daikon: 60)",
  "sun": "Full sun",
  "spacing": "2 in",
  "tips": "The fastest crop there is — great for kids. Get pithy and hot in warm weather.",
  "wiki": "Radish",
  "hydro": "seeds",
  "hydro_note": "Possible from seed in media beds, and very fast. Microgreens are the easiest option.",
  "img": "images/radish.jpg",
  "credit": {
   "file": "Radish_3371103037_4ab07db0bf_o.jpg",
   "artist": "Self, en:User:Jengod",
   "license": "Public domain",
   "source": "https://commons.wikimedia.org/wiki/File:Radish_3371103037_4ab07db0bf_o.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   1,
   2,
   3,
   9,
   10,
   11
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   11,
   12,
   1,
   2,
   3,
   4,
   5
  ],
  "id": "turnip",
  "name": "Turnips",
  "cat": "vegetable",
  "season": "cool",
  "days": "40–60 days",
  "sun": "Full sun",
  "spacing": "4 in",
  "tips": "Harvest small (golf ball size) for the sweetest roots. Greens are delicious.",
  "wiki": "Turnip",
  "hydro": "seeds",
  "hydro_note": "Greens grow well from seed. Roots need a media bed.",
  "img": "images/turnip.jpg",
  "credit": {
   "file": "Turnip_2622027.jpg",
   "artist": "thebittenword.com",
   "license": "CC BY 2.0",
   "source": "https://commons.wikimedia.org/wiki/File:Turnip_2622027.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   1,
   2,
   3,
   9,
   10,
   11,
   12
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   1,
   2,
   3,
   4,
   5,
   10,
   11,
   12
  ],
  "id": "cilantro",
  "name": "Cilantro",
  "cat": "herb",
  "season": "cool",
  "days": "45–70 days",
  "sun": "Full sun to part shade",
  "spacing": "4–6 in",
  "tips": "Bolts immediately in heat — it's a winter herb here. Let some go to seed for coriander and free volunteers next fall.",
  "wiki": "Coriander",
  "hydro": "seeds",
  "hydro_note": "Grows well from seed in hydroponics, and indoor temperatures slow bolting.",
  "img": "images/cilantro.jpg",
  "credit": {
   "file": "Bunches of coriander leaves.jpg",
   "artist": "Kpsudeep",
   "license": "CC BY-SA 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:Bunches_of_coriander_leaves.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   1,
   2,
   3,
   9,
   10
  ],
  "transplant": [],
  "plant": [],
  "harvest": [
   3,
   4,
   5,
   6,
   11,
   12
  ],
  "id": "dill",
  "name": "Dill",
  "cat": "herb",
  "season": "cool",
  "days": "40–60 days",
  "sun": "Full sun",
  "spacing": "12 in",
  "tips": "Attracts beneficial insects and swallowtail caterpillars. Doesn't transplant well — sow direct.",
  "wiki": "Dill",
  "hydro": "seeds",
  "hydro_note": "Grows from seed, but gets tall. Try dwarf varieties like 'Fernleaf'.",
  "img": "images/dill.jpg",
  "credit": {
   "file": "Starr-081031-0431-Anethum graveolens-leaves-Makawao-Maui (24631288220).jpg",
   "artist": "Forest and Kim Starr",
   "license": "CC BY 3.0 us",
   "source": "https://commons.wikimedia.org/wiki/File:Starr-081031-0431-Anethum_graveolens-leaves-Makawao-Maui_(24631288220).jpg"
  }
 },
 {
  "indoors": [],
  "sow": [
   2,
   3,
   9,
   10
  ],
  "transplant": [
   2,
   3,
   4,
   9,
   10,
   11
  ],
  "plant": [],
  "harvest": [
   1,
   2,
   3,
   4,
   5,
   6,
   7,
   10,
   11,
   12
  ],
  "id": "parsley",
  "name": "Parsley",
  "cat": "herb",
  "season": "cool",
  "days": "70–90 days from seed",
  "sun": "Full sun to part shade",
  "spacing": "8–10 in",
  "tips": "Slow to germinate — soak seed overnight. Biennial; lasts about a year before flowering.",
  "wiki": "Parsley",
  "hydro": "seeds",
  "hydro_note": "Grows well from seed once it sprouts (germination is slow). Productive for months.",
  "img": "images/parsley.jpg",
  "credit": {
   "file": "Parsley Leaves.jpg",
   "artist": "Etopalrux",
   "license": "CC BY-SA 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:Parsley_Leaves.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   1,
   2,
   3,
   10,
   11
  ],
  "harvest": [
   3,
   4,
   5
  ],
  "id": "artichoke",
  "name": "Artichoke",
  "cat": "vegetable",
  "season": "perennial",
  "days": "Perennial; first buds the next spring",
  "sun": "Full sun",
  "spacing": "4–6 ft",
  "tips": "A beautiful perennial that lives 5+ years. Cut back hard after harvest; summer dormancy in the heat is normal.",
  "wiki": "Artichoke",
  "hydro": "no",
  "hydro_note": "A large perennial that needs soil.",
  "img": "images/artichoke.jpg",
  "credit": {
   "file": "Artichoke_J1.jpg",
   "artist": "Jamain",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Artichoke_J1.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   1,
   2
  ],
  "harvest": [
   2,
   3,
   4
  ],
  "id": "asparagus",
  "name": "Asparagus",
  "cat": "vegetable",
  "season": "perennial",
  "days": "Light harvest in year 2, full from year 3",
  "sun": "Full sun",
  "spacing": "12–18 in",
  "tips": "Plant crowns in a trench. Choose low-chill types like 'UC 157' bred for California. Lets ferns grow all summer to feed the roots.",
  "wiki": "Asparagus",
  "hydro": "no",
  "hydro_note": "A perennial crown crop that takes years to produce and needs soil.",
  "img": "images/asparagus.jpg",
  "credit": {
   "file": "Asparagus-Bundle.jpg",
   "artist": "Evan-Amos",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Asparagus-Bundle.jpg"
  }
 },
 {
  "indoors": [
   2,
   3
  ],
  "sow": [
   4,
   5,
   6,
   7
  ],
  "transplant": [
   4,
   5,
   6,
   7
  ],
  "plant": [],
  "harvest": [
   5,
   6,
   7,
   8,
   9,
   10
  ],
  "id": "basil",
  "name": "Basil",
  "cat": "herb",
  "season": "warm",
  "days": "50–70 days",
  "sun": "Full sun",
  "spacing": "12 in",
  "tips": "Pinch flower buds to keep it leafy. Great companion to tomatoes. Dies at first frost.",
  "wiki": "Basil",
  "hydro": "both",
  "hydro_note": "The #1 hydroponic herb. Grows fast from seed, and tip cuttings root in water in about a week.",
  "img": "images/basil.jpg",
  "credit": {
   "file": "Ocimum_basilicum_8zz.jpg",
   "artist": "Photo by David J. Stang",
   "license": "CC BY-SA 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:Ocimum_basilicum_8zz.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   2,
   3,
   4,
   9,
   10,
   11
  ],
  "harvest": [
   1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12
  ],
  "id": "rosemary",
  "name": "Rosemary",
  "cat": "herb",
  "season": "perennial",
  "days": "Perennial shrub",
  "sun": "Full sun",
  "spacing": "2–4 ft",
  "tips": "Mediterranean native that thrives on neglect in Claremont. Needs good drainage — don't overwater.",
  "wiki": "Rosemary",
  "hydro": "cuttings",
  "hydro_note": "Cuttings are faster than seed. Needs well-aerated media and hates soggy roots.",
  "img": "images/rosemary.jpg",
  "credit": {
   "file": "Rosemary_in_bloom.JPG",
   "artist": "Margalob",
   "license": "CC BY-SA 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:Rosemary_in_bloom.JPG"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   2,
   3,
   4,
   9,
   10,
   11
  ],
  "harvest": [
   1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12
  ],
  "id": "thyme",
  "name": "Thyme",
  "cat": "herb",
  "season": "perennial",
  "days": "Perennial",
  "sun": "Full sun",
  "spacing": "12 in",
  "tips": "Drought tolerant and pollinator friendly. Trim after flowering to keep it compact.",
  "wiki": "Thyme",
  "hydro": "cuttings",
  "hydro_note": "Grows from cuttings in media beds. Seed is very slow.",
  "img": "images/thyme.jpg",
  "credit": {
   "file": "Thyme-Bundle.jpg",
   "artist": "Evan-Amos",
   "license": "CC0",
   "source": "https://commons.wikimedia.org/wiki/File:Thyme-Bundle.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   2,
   3,
   4,
   5,
   9,
   10
  ],
  "harvest": [
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11
  ],
  "id": "mint",
  "name": "Mint",
  "cat": "herb",
  "season": "perennial",
  "days": "Perennial",
  "sun": "Part shade",
  "spacing": "Grow in a pot",
  "tips": "Aggressively spreads — keep it in a container. Appreciates afternoon shade inland.",
  "wiki": "Mentha",
  "hydro": "cuttings",
  "hydro_note": "Cuttings root in plain water within days, and it thrives in any hydroponic system.",
  "img": "images/mint.jpg",
  "credit": {
   "file": "Mentha_spicata-IMG_6186.jpg",
   "artist": "C T Johansson",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Mentha_spicata-IMG_6186.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   10,
   11,
   1,
   2
  ],
  "harvest": [
   3,
   4,
   5,
   6,
   7
  ],
  "id": "strawberry",
  "name": "Strawberry",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fall-planted: fruit next spring",
  "sun": "Full sun",
  "spacing": "12 in",
  "tips": "In Southern California, plant in fall (Oct–Nov) like the commercial growers for the best spring crop. Day-neutral varieties like 'Albion' or 'Seascape' fruit longest. Replant every 2–3 years.",
  "wiki": "Strawberry",
  "hydro": "cuttings",
  "hydro_note": "Grown commercially in hydroponics. Start from runners (daughter plants) or bare-root crowns. Seed is slow and unreliable. Day-neutral varieties work best.",
  "img": "images/strawberry.jpg",
  "credit": {
   "file": "Garden_strawberry_(Fragaria_×_ananassa)_single2.jpg",
   "artist": "Ivar Leidus",
   "license": "CC BY-SA 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:Garden_strawberry_(Fragaria_%C3%97_ananassa)_single2.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   10,
   11,
   12,
   1,
   2,
   3
  ],
  "harvest": [
   4,
   5,
   6
  ],
  "id": "blueberry",
  "name": "Blueberry",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 2+",
  "sun": "Full sun (afternoon shade inland)",
  "spacing": "4–5 ft",
  "tips": "Choose low-chill Southern Highbush ('Sunshine Blue', 'Misty', 'O'Neal'). Needs acidic soil — grow in containers with acid mix, since Claremont soil and water are alkaline.",
  "wiki": "Blueberry",
  "hydro": "cuttings",
  "hydro_note": "Grown commercially in substrate (coco coir) from rooted cuttings. Advanced for home growers because of the strict acidic pH (4.5–5.5).",
  "img": "images/blueberry.jpg",
  "credit": {
   "file": "Blueberries.jpg",
   "artist": "The original Uploader was Oven Fresh at English Wikipedia",
   "license": "Public domain",
   "source": "https://commons.wikimedia.org/wiki/File:Blueberries.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   12,
   1,
   2,
   3
  ],
  "harvest": [
   5,
   6,
   7
  ],
  "id": "blackberry",
  "name": "Blackberry",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 2",
  "sun": "Full sun",
  "spacing": "3–5 ft",
  "tips": "Thornless low-chill varieties like 'Ouachita' and 'Navaho' do well. Cut out canes that have fruited each summer.",
  "wiki": "Blackberry",
  "hydro": "cuttings",
  "hydro_note": "Grown commercially in substrate from rooted tip cuttings. Advanced, and needs a lot of space.",
  "img": "images/blackberry.jpg",
  "credit": {
   "file": "Ripe,_ripening,_and_green_blackberries.jpg",
   "artist": "Ragesoss",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Ripe,_ripening,_and_green_blackberries.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   12,
   1,
   2,
   3
  ],
  "harvest": [
   5,
   6,
   7,
   9,
   10,
   11
  ],
  "id": "raspberry",
  "name": "Raspberry",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit first year (everbearing)",
  "sun": "Full sun, afternoon shade",
  "spacing": "2–3 ft",
  "tips": "Use low-chill varieties ('Bababerry', 'Oregon 1030', 'Heritage'). Everbearers give a summer and a fall crop.",
  "wiki": "Raspberry",
  "hydro": "cuttings",
  "hydro_note": "Grown commercially in substrate pots from rooted canes. Advanced at home.",
  "img": "images/raspberry.jpg",
  "credit": {
   "file": "Raspberry_-_halved_(Rubus_idaeus).jpg",
   "artist": "Ivar Leidus",
   "license": "CC BY-SA 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:Raspberry_-_halved_(Rubus_idaeus).jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   1,
   2,
   3
  ],
  "harvest": [
   7,
   8,
   9
  ],
  "id": "grape",
  "name": "Grapes",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 2–3",
  "sun": "Full sun",
  "spacing": "6–8 ft on trellis",
  "tips": "Hot inland summers are ideal. 'Flame Seedless', 'Thompson', and muscats do well. Prune hard every winter.",
  "wiki": "Grape",
  "hydro": "no",
  "hydro_note": "A long-lived woody vine. Cuttings root in water but should then go in the ground.",
  "img": "images/grape.jpg",
  "credit": {
   "file": "Grapes,_Rostov-on-Don,_Russia.jpg",
   "artist": "Vyacheslav Argenberg",
   "license": "CC BY 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:Grapes,_Rostov-on-Don,_Russia.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   4,
   5,
   6
  ],
  "harvest": [
   7,
   8,
   9,
   10,
   11,
   12
  ],
  "id": "passionfruit",
  "name": "Passion Fruit",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 1–2",
  "sun": "Full sun",
  "spacing": "10 ft on fence",
  "tips": "Vigorous vine for a fence. 'Frederick' is a reliable self-fertile variety. Protect from hard frost when young.",
  "wiki": "Passiflora edulis",
  "hydro": "no",
  "hydro_note": "A vigorous perennial vine. Grow it in the ground.",
  "img": "images/passionfruit.jpg",
  "credit": {
   "file": "Passionfruit (whole and half).jpg",
   "artist": "Azreey",
   "license": "CC BY-SA 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:Passionfruit_(whole_and_half).jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   4,
   5,
   6
  ],
  "harvest": [
   7,
   8,
   9,
   10
  ],
  "id": "dragonfruit",
  "name": "Dragon Fruit",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 2–3",
  "sun": "Full sun to part shade",
  "spacing": "Post per plant",
  "tips": "A climbing cactus that needs a sturdy post. Hand-pollinate night blooms for better fruit set. Cover on frosty nights.",
  "wiki": "Pitaya",
  "hydro": "no",
  "hydro_note": "A cactus. Cuttings root easily in dry soil, but it rots in hydroponic conditions.",
  "img": "images/dragonfruit.jpg",
  "credit": {
   "file": "Pitaya_cross_section_ed2.jpg",
   "artist": "SMasters",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Pitaya_cross_section_ed2.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   3,
   4,
   5,
   9,
   10
  ],
  "harvest": [
   12,
   1,
   2,
   3,
   4,
   5,
   6
  ],
  "id": "orange",
  "name": "Orange (Navel & Valencia)",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 2–3",
  "sun": "Full sun",
  "spacing": "12–20 ft (dwarf 8 ft)",
  "tips": "Claremont sits in historic citrus country. Navels ripen in winter, Valencias spring–summer. Plant in spring after frost danger passes.",
  "wiki": "Orange (fruit)",
  "hydro": "no",
  "hydro_note": "A fruit tree. Grow it in the ground or a large container of soil.",
  "img": "images/orange.jpg",
  "credit": {
   "file": "Oranges_-_whole-halved-segment.jpg",
   "artist": "Ivar Leidus",
   "license": "CC BY-SA 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:Oranges_-_whole-halved-segment.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   3,
   4,
   5,
   9,
   10
  ],
  "harvest": [
   1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   9,
   10,
   11,
   12
  ],
  "id": "lemon",
  "name": "Lemon",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 2",
  "sun": "Full sun",
  "spacing": "10–15 ft",
  "tips": "'Improved Meyer' is the most cold-tolerant and compact. 'Eureka' and 'Lisbon' fruit nearly year-round.",
  "wiki": "Lemon",
  "hydro": "no",
  "hydro_note": "A fruit tree. 'Improved Meyer' does well in a large soil container instead.",
  "img": "images/lemon.jpg",
  "credit": {
   "file": "P1030323.JPG",
   "artist": "Elena Chochkova",
   "license": "CC BY-SA 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:P1030323.JPG"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   3,
   4,
   5,
   9,
   10
  ],
  "harvest": [
   11,
   12,
   1,
   2,
   3,
   4
  ],
  "id": "mandarin",
  "name": "Mandarin / Tangerine",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 2–3",
  "sun": "Full sun",
  "spacing": "10–15 ft",
  "tips": "Plant a few varieties ('Satsuma', 'Clementine', 'Gold Nugget', 'Pixie') to spread the harvest over 6 months.",
  "wiki": "Mandarin orange",
  "hydro": "no",
  "hydro_note": "A fruit tree. Grow it in the ground or a large container of soil.",
  "img": "images/mandarin.jpg",
  "credit": {
   "file": "Citrus_reticulata_April_2013_Nordbaden.JPG",
   "artist": "4028mdk09",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Citrus_reticulata_April_2013_Nordbaden.JPG"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   4,
   5,
   9
  ],
  "harvest": [
   8,
   9,
   10,
   11,
   12,
   1
  ],
  "id": "lime",
  "name": "Lime",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 2",
  "sun": "Full sun",
  "spacing": "10–15 ft",
  "tips": "The most frost-tender citrus — plant in a warm, protected spot and cover on frosty nights. 'Bearss' is the common choice.",
  "wiki": "Persian lime",
  "hydro": "no",
  "hydro_note": "A fruit tree. Grow it in the ground or a large container of soil.",
  "img": "images/lime.jpg",
  "credit": {
   "file": "Starr-140117-3997-Citrus_latifolia-Tahitian_fruit_and_leaves-Hawea_Pl_Olinda-Maui_(24612312943).jpg",
   "artist": "Forest and Kim Starr",
   "license": "CC BY 3.0 us",
   "source": "https://commons.wikimedia.org/wiki/File:Starr-140117-3997-Citrus_latifolia-Tahitian_fruit_and_leaves-Hawea_Pl_Olinda-Maui_(24612312943).jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   3,
   4,
   5,
   6
  ],
  "harvest": [
   3,
   4,
   5,
   6,
   7,
   8,
   9
  ],
  "id": "avocado",
  "name": "Avocado",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 3–4 (grafted)",
  "sun": "Full sun",
  "spacing": "20+ ft (or 'Wurtz' dwarf)",
  "tips": "Plant in spring so roots establish before winter. 'Hass' tolerates light frost; 'Bacon' and 'Fuerte' are hardier. Needs excellent drainage — plant on a mound.",
  "wiki": "Avocado",
  "hydro": "no",
  "hydro_note": "A large tree. Growing a pit in water is a fun project, but it won't fruit that way.",
  "img": "images/avocado.jpg",
  "credit": {
   "file": "Persea_americana_fruit_2.JPG",
   "artist": "B.navez",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Persea_americana_fruit_2.JPG"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   1,
   2,
   3,
   4,
   5
  ],
  "harvest": [
   6,
   7,
   8,
   9,
   10
  ],
  "id": "fig",
  "name": "Fig",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 1–2",
  "sun": "Full sun",
  "spacing": "10–15 ft",
  "tips": "One of the easiest fruit trees for inland SoCal. 'Black Mission', 'Brown Turkey', and 'Kadota' give a June breba crop plus a main late-summer crop.",
  "wiki": "Common fig",
  "hydro": "no",
  "hydro_note": "A fruit tree. Cuttings root easily in water for propagation, then plant in soil.",
  "img": "images/fig.jpg",
  "credit": {
   "file": "Fig (Ficus carica) fruit halved.jpg",
   "artist": "Ivar Leidus",
   "license": "CC BY-SA 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:Fig_(Ficus_carica)_fruit_halved.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   12,
   1,
   2
  ],
  "harvest": [
   5,
   6,
   7,
   8
  ],
  "id": "peach",
  "name": "Peach",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 2–3",
  "sun": "Full sun",
  "spacing": "12–15 ft",
  "tips": "Plant bare-root in winter. Pick LOW-CHILL varieties (under ~400 hours): 'Babcock', 'Tropic Snow', 'Florida Prince', 'Mid-Pride'. Spray for peach leaf curl in winter.",
  "wiki": "Peach",
  "hydro": "no",
  "hydro_note": "A deciduous fruit tree. Needs soil and winter chill.",
  "img": "images/peach.jpg",
  "credit": {
   "file": "Autumn Red peaches.jpg",
   "artist": "Jack Dykinga, USDA",
   "license": "Public domain",
   "source": "https://commons.wikimedia.org/wiki/File:Autumn_Red_peaches.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   12,
   1,
   2
  ],
  "harvest": [
   6,
   7,
   8
  ],
  "id": "nectarine",
  "name": "Nectarine",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 2–3",
  "sun": "Full sun",
  "spacing": "12–15 ft",
  "tips": "Low-chill picks: 'Snow Queen', 'Panamint', 'Double Delight'. Same winter care as peaches.",
  "wiki": "Nectarine",
  "hydro": "no",
  "hydro_note": "A deciduous fruit tree. Needs soil and winter chill.",
  "img": "images/nectarine.jpg",
  "credit": {
   "file": "Nectarine on white.jpg",
   "artist": "Rhododendrites",
   "license": "CC BY-SA 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:Nectarine_on_white.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   12,
   1,
   2
  ],
  "harvest": [
   5,
   6,
   7
  ],
  "id": "apricot",
  "name": "Apricot",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 3",
  "sun": "Full sun",
  "spacing": "15 ft",
  "tips": "'Blenheim' is the classic, but low-chill 'Gold Kist' is more reliable in 10a.",
  "wiki": "Apricot",
  "hydro": "no",
  "hydro_note": "A deciduous fruit tree. Needs soil and winter chill.",
  "img": "images/apricot.jpg",
  "credit": {
   "file": "Apricot_and_cross_section.jpg",
   "artist": "Fir0002",
   "license": "GFDL 1.2",
   "source": "https://commons.wikimedia.org/wiki/File:Apricot_and_cross_section.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   12,
   1,
   2
  ],
  "harvest": [
   6,
   7,
   8
  ],
  "id": "plum",
  "name": "Plum & Pluot",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 3",
  "sun": "Full sun",
  "spacing": "12–15 ft",
  "tips": "'Santa Rosa' and 'Satsuma' Japanese plums are low-chill. Pluots like 'Flavor King' may need a pollinator.",
  "wiki": "Plum",
  "hydro": "no",
  "hydro_note": "A deciduous fruit tree. Needs soil and winter chill.",
  "img": "images/plum.jpg",
  "credit": {
   "file": "Plums_African_Rose_-_whole,_halved_and_slice.jpg",
   "artist": "Ivar Leidus",
   "license": "CC BY-SA 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:Plums_African_Rose_-_whole,_halved_and_slice.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   12,
   1,
   2
  ],
  "harvest": [
   6,
   7,
   8,
   9,
   10
  ],
  "id": "apple",
  "name": "Apple (low-chill)",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 2–4",
  "sun": "Full sun",
  "spacing": "8–15 ft",
  "tips": "Only low-chill apples fruit here: 'Anna' + 'Dorsett Golden' (pollinate each other), 'Fuji', 'Pink Lady', 'Gala'.",
  "wiki": "Apple",
  "hydro": "no",
  "hydro_note": "A deciduous fruit tree. Needs soil and winter chill.",
  "img": "images/apple.jpg",
  "credit": {
   "file": "Pink_lady_and_cross_section.jpg",
   "artist": "fir0002  flagstaffotos [at] gmail.com\n\t\tCanon 20D + Sigma 150mm f/2.8",
   "license": "GFDL 1.2",
   "source": "https://commons.wikimedia.org/wiki/File:Pink_lady_and_cross_section.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   1,
   2,
   3,
   4,
   5
  ],
  "harvest": [
   9,
   10,
   11
  ],
  "id": "pomegranate",
  "name": "Pomegranate",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 2–3",
  "sun": "Full sun",
  "spacing": "10–15 ft",
  "tips": "Thrives on heat and drought — nearly perfect for Claremont. 'Wonderful' is the classic; 'Parfianka' and 'Eversweet' are softer-seeded.",
  "wiki": "Pomegranate",
  "hydro": "no",
  "hydro_note": "A fruit shrub or tree. Cuttings root easily, then plant in soil.",
  "img": "images/pomegranate.jpg",
  "credit": {
   "file": "Pomegranate_Juice_(2019).jpg",
   "artist": "Augustus Binu : flickr",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Pomegranate_Juice_(2019).jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   12,
   1,
   2
  ],
  "harvest": [
   10,
   11,
   12
  ],
  "id": "persimmon",
  "name": "Persimmon",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 3",
  "sun": "Full sun",
  "spacing": "15–20 ft",
  "tips": "'Fuyu' is eaten crisp like an apple; 'Hachiya' must be fully soft. Beautiful fall color and very low maintenance.",
  "wiki": "Persimmon",
  "hydro": "no",
  "hydro_note": "A fruit tree. Grow it in the ground.",
  "img": "images/persimmon.jpg",
  "credit": {
   "file": "Fuyu_persimmon_fruits,_one_cut_open.jpg",
   "artist": "Frank Schulenburg",
   "license": "CC BY-SA 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:Fuyu_persimmon_fruits,_one_cut_open.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   3,
   4,
   5,
   9,
   10
  ],
  "harvest": [
   3,
   4,
   5
  ],
  "id": "loquat",
  "name": "Loquat",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 2–3 (grafted)",
  "sun": "Full sun",
  "spacing": "15 ft",
  "tips": "Evergreen and practically carefree. One of the first fruits of spring.",
  "wiki": "Loquat",
  "hydro": "no",
  "hydro_note": "A fruit tree. Grow it in the ground.",
  "img": "images/loquat.jpg",
  "credit": {
   "file": "Loquat-0.jpg",
   "artist": "Aftabbanoori",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Loquat-0.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   3,
   4,
   5,
   9,
   10
  ],
  "harvest": [
   10,
   11,
   12
  ],
  "id": "feijoa",
  "name": "Feijoa (Pineapple Guava)",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 2–3",
  "sun": "Full sun",
  "spacing": "10 ft",
  "tips": "Drought tolerant evergreen shrub; the flower petals are edible too. Harvest fruit as it drops.",
  "wiki": "Feijoa",
  "hydro": "no",
  "hydro_note": "A fruiting shrub. Grow it in the ground.",
  "img": "images/feijoa.jpg",
  "credit": {
   "file": "Goiaba-serrana,_ou_guarobi_(do_guarani_'fruto_verde'),_Feijoa_sellowiana,_em_Bagé,_RS,_Brasil_-_55238473195.jpg",
   "artist": "Gabriel Collares",
   "license": "CC BY 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:Goiaba-serrana,_ou_guarobi_(do_guarani_%27fruto_verde%27),_Feijoa_sellowiana,_em_Bag%C3%A9,_RS,_Brasil_-_55238473195.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   12,
   1,
   2,
   3
  ],
  "harvest": [
   4,
   5,
   6
  ],
  "id": "mulberry",
  "name": "Mulberry",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 1–2",
  "sun": "Full sun",
  "spacing": "15–30 ft (or dwarf)",
  "tips": "Fast and prolific. Dwarf 'Dwarf Everbearing' fits small yards. Don't plant over a patio — the fruit stains.",
  "wiki": "Morus nigra",
  "hydro": "no",
  "hydro_note": "A fruit tree. Cuttings root readily, then plant in soil.",
  "img": "images/mulberry.jpg",
  "credit": {
   "file": "Black mulberry fruit (Morus nigra).jpg",
   "artist": "Beko",
   "license": "CC BY-SA 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:Black_mulberry_fruit_(Morus_nigra).jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   12,
   1,
   2
  ],
  "harvest": [
   8,
   9,
   10
  ],
  "id": "jujube",
  "name": "Jujube",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 1–2",
  "sun": "Full sun",
  "spacing": "10–15 ft",
  "tips": "Loves heat and alkaline soil, very drought tolerant. 'Li' and 'Lang' are popular varieties.",
  "wiki": "Jujube",
  "hydro": "no",
  "hydro_note": "A fruit tree. Grow it in the ground.",
  "img": "images/jujube.jpg",
  "credit": {
   "file": "Jujube fruit.jpg",
   "artist": "Jacqueline Gabardy",
   "license": "CC BY-SA 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:Jujube_fruit.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   3,
   4,
   5,
   6
  ],
  "harvest": [
   10,
   11,
   12
  ],
  "id": "olive",
  "name": "Olive",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 3–4",
  "sun": "Full sun",
  "spacing": "20 ft",
  "tips": "Long-lived and drought tolerant. Fruit must be cured (brined) before eating. 'Arbequina' is compact and self-fertile.",
  "wiki": "Olive",
  "hydro": "no",
  "hydro_note": "A long-lived tree. Grow it in the ground.",
  "img": "images/olive.jpg",
  "credit": {
   "file": "Olivesfromjordan.jpg",
   "artist": "en:User:Nickfraser",
   "license": "CC BY-SA 3.0",
   "source": "https://commons.wikimedia.org/wiki/File:Olivesfromjordan.jpg"
  }
 },
 {
  "indoors": [],
  "sow": [],
  "transplant": [],
  "plant": [
   4,
   5,
   6
  ],
  "harvest": [
   8,
   9,
   10,
   11,
   12
  ],
  "id": "guava",
  "name": "Guava (tropical)",
  "cat": "fruit",
  "season": "perennial",
  "days": "Fruit year 2–3",
  "sun": "Full sun",
  "spacing": "10–15 ft",
  "tips": "Frost tender when young — plant against a south-facing wall and cover during cold snaps. Strawberry guava is hardier.",
  "wiki": "Guava",
  "hydro": "no",
  "hydro_note": "A fruit tree. Grow it in the ground or a large soil container.",
  "img": "images/guava.jpg",
  "credit": {
   "file": "Guava_pink_fruit.jpg",
   "artist": "Ivar Leidus",
   "license": "CC BY-SA 4.0",
   "source": "https://commons.wikimedia.org/wiki/File:Guava_pink_fruit.jpg"
  }
 }
];
